#!/bin/sh /etc/rc.common

START=21

update_wireless_settings(){
  uci set wireless.@wifi-device[0].band='2g'
  uci set wireless.@wifi-device[0].channel='1'

  uci set wireless.@wifi-iface[0].ssid='openwrt-openwifi'
  uci set wireless.@wifi-iface[0].network='wlan'
  uci set wireless.@wifi-iface[0].disabled='0'
  uci commit wireless
}

boot() {
	update_wireless_settings
}
